llm_config:
  tool_llm:
    name: cogito:3b
    provider: ollama
    temperature: 0.3
  vision_llm:
    name: gemma3:12b
    provider: ollama
    temperature: 0.2
tools:
  web_search: false
  weather: true
  math: false
